---
title: HW6 Website
subtitle: Analysis on Instacart Dataset
---



In HW6, Analysis on Instacart Dataset was conducted.

Collaborators for this project:

Xiangyu Shi (UNI: xs2329 )
Yulan Zhang (UNI: yz3306)

##Data Description & Processing Steps

In this project, we are interested in the **“The Instacart Online Grocery Shopping Dataset 2017”** dataset which contains over 3 million online grocery orders from more than 200,000 Instacart users. Since this dataset is quite extensive, we only focus on order status in the following 4 departments: `deli`, `frozen`, `produce` and `bakery`. Out of the 15 variables included in this dataset, we limit the variables of interest to only :

- `order_dow` : the day of the week on which the order was placed

- `order_hour_of_day`: the hour of the day on which the order was placed

- `department`: the name of the department

- `product_name`: name of the product

- `aisle`: the name of the aislef

In **problem 1**, figures are created using plotly for interactive graphics and presented in a flexdashboard. 
In **problem 2**, a shiny-enabled dashboard is created to elaborate on the work done in Problem 1.

Download the data used for this project [here](http://jeffgoldsmith.com/DSI/data/instacart_train_data.csv.zip).


###Problem 1

**A flexdashboard created using plotly is [here](https://fionalav.github.io/p8105_hw6_xs2329_yz3306/).**


- In **Figure A**, we analyzed the total number of orders in each department and presented the most popular products in each department during a week. The bar graph is ordered by the number of orders with distinct colors indicating on which day of the week that item was ordered. 

- In **Figure B**, we analyzed the hour of the day on which the order was placed in each department. From the box plot, we observed a consistant pattern that the medians across the 4 departments are all within 10-15 hours during the day, and all are skewed to the left.

- In **Figure C**, we further analyzed the nubmer of orders placed in each department during the week. We obeserve that the number of orders for the 4 departments remain a consistant pattern regardless of the day of the week. 

We will take a closer look for variables within each department using shiny. 
 
###Problem 2

**A shiny-enabled dashboard created using Shiny is [here](https://fionalav.shinyapps.io/hw6_shiny/).**

- In **graph A**, we updated the graph A in problem 1. We added the selectorInput Widget in the sidebar for `Day of week` Variable. In this case, we can visualize the most popular item from each department on each day of week, by selecting in the day of week widget. For instance, on Sunday, the most popular product in bakery department is "100% Whole Wheat Bread", while in Monday, the most popular product in Bakery department is "Whole Wheat Bread".

- In **graph B**, we updated the graph B in problem 1. We added the RadioButton Widget in the sidebar for `Department` Variable. In this case, we can visualize the hour of the day the order was placed on each aisle within its own department, by selecting individual department in the sidebar widget. For instance, in Department "Produce", there are six aisles involved. We can visualize each aisle's respective distribution of ordering hour of day.

- In **graph C**, we updated the graph C in problem 1. We also used the RadioButton Widget in the sidebar for `Department` Variable. In this case, we can visualize the trend of number of products ordered over the week for each department, by selecting individual department in the sidebar widget. For instance, in Department "Bakery", orders are placed the most on Sunday. The number of orders decreases to the lowest(5346) on Wednesday and increases back to highest(7233) on Sunday.



###Note
GitHub repo for the flexdashboard is [here](https://github.com/Fionalav/p8105_hw6_xs2329_yz3306).\
GitHub repo for the Shiny-enabled dashboard is [here](https://github.com/Fionalav/P8105_hw6_shiny).\
GitHub repo for the website is [here](https://github.com/Fionalav/p8105_hw6_website).\



